# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 18:27
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='正文'),
        ),
    ]
