# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-01 00:09
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180131_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='评论'),
        ),
    ]
