"""
Django settings for first_blog project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xshwb+1z)g-4o%&s4klnboce1yz!d###pu02q=qtn6tkn1c38u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'blog.apps.BlogConfig',
    'markdown',
    'pygments',
    'blog',
    'comments',
    'DjangoUeditor',
    #'xadmin',
    'crispy_forms'
]

MIDDLEWARE = [
     # 站点缓存 ， 注意必须在第一个位置    
   'django.middleware.cache.UpdateCacheMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     # 站点缓存, 注意必须在最后一个位置
    'django.middleware.cache.FetchFromCacheMiddleware',
]

MIDDLEWARE_CLASSES = [
     # 站点缓存 ， 注意必须在第一个位置
   'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     # 站点缓存, 注意必须在最后一个位置
    'django.middleware.cache.FetchFromCacheMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

# CACHES = {
#         "default": {
#             "BACKEND": "django_rediscache.RedisCache",
#             #'BACKEND': 'redis_cache.RedisCache',
#             #'LOCATION': '127.0.0.1:6379',
#             "LOCATION": "redis://123.56.12.78:6379",
#             "OPTIONS": {
#                 'DB': 1,
#                 #'TIMEOUT': 600,
#                 #'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
#                 'CLIENT_CLASS': "django_redis.client.DefaultClient",
#                 'PASSWORD' : "redhat"
#
#                 },
#             "KEY_PREFIX":"example"
#             },
#         }

SESSION_COOKIE_AGE=30 * 60
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'firstblog',
        'USER':'root',
        'PASSWORD':'wkl123',
        'HOST':'172.16.1.109',
        'PORT':'3306',
        'OPTIONS': {
            'autocommit': True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ =False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
LOGIN_REDIRECT_URL = '/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, 'images').replace('\\', '/'),
)



MEDIA_URL = '/media/'
MEDIA_ROOT =  os.path.join(BASE_DIR, "media")
