# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-31 09:43
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='正文'),
        ),
    ]
