# Generated by Django 3.0.3 on 2020-02-28 15:09

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180131_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='正文'),
        ),
    ]
